#alias
alias gcp='gpick'
alias gpc='gpick'
alias c='clear'
alias n='nano'
alias v='vim'
alias tx='tmux'
alias t='tmux attach -t0'
alias t1='tmux attach -t1'
alias ta='tmux attach -t'
alias tl='tmux ls'
alias h='htop'
alias cc='ccache -s'
alias s='source'
alias q='exit'
alias e='echo'
alias du='du -h'
alias dus='du -sh'
alias d='df -h'
alias wh='which'
alias rmrf='rm -rf'
alias path='echo -e ${PATH//:/\\n}'
alias myip="curl http://ipecho.net/plain; echo"
alias st2='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'
alias rs='repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j'
alias f='free -h'
alias sshn='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias gs='gcloud cloud-shell ssh'
