#curl https://raw.githubusercontent.com/Apon77/linux/refs/heads/junk/others/docker-chromium.yaml --create-dirs -o linux/others/docker-chromium.yaml #for temp env where git is not installed
#docker compose -f ~/linux/others/docker-chromium.yaml up -d
#now access ip:5800 from browser to access docker chromium

version: '3'
services:
  chromium:
    image: jlesage/chromium
    ports:
      - "5800:5800"
    volumes:
      - "/docker/appdata/chromium:/config:rw"
