#!/bin/bash
read -p 'Location to test(ex: /tmp): ' testing_location
read -p 'Size of file(ex: 1G): ' testing_size

#testing_location=/tmp
#testing_size=1G

# server throughput (write speed)
echo 'Server throughput(write)...'
sudo dd if=/dev/zero of=$testing_location/test1.img bs=$testing_size count=1 oflag=dsync

# server latency
echo '
Server latency(write)...'
sudo dd if=/dev/zero of=$testing_location/test2.img bs=512 count=1000 oflag=dsync

sudo rm -rf $testing_location/test1.img $testing_location/test2.img
