#!/bin/bash
read -p 'Swap file location(ex: /mnt/swapfile): ' swap_file
read -p 'Swap file size(ex: 8G): ' swap_file_size

#swap_file=/mnt/swapfile
#swap_file_size=2G

sudo swapon --show
sudo fallocate -l $swap_file_size $swap_file
sudo chmod 600 $swap_file
sudo mkswap $swap_file
sudo swapon $swap_file
#sudo vim /etc/fstab
#/mnt/swapfile swap swap defaults 0 0
sudo swapon --show
#cat /proc/sys/vm/swappiness
#sudo vim /etc/sysctl.conf or sudo vim /etc/sysctl.d/99-swappiness.conf
#Add this line
#vm.swappiness=10    #swappiness 10 is good for server
#sudo sysctl vm.swappiness=10

#turn off
#sudo swapoff $swap_file
#sudo rm -f $swap_file
