#!/bin/bash
sudo apt -qq update || apt -qq update
sudo apt -qq install xfce4 || apt -qq install xfce4
sudo apt -qq install tightvncserver || apt -qq install tightvncserver

mkdir -p ~/.vnc
echo '#!/bin/bash
xrdb $HOME/.Xresources
startxfce4 &' > ~/.vnc/xstartup
chmod +x ~/.vnc/xstartup

vncserver :1
