#!/bin/bash
sudo apt update || apt update
sudo apt install xfce4 || apt install xfce4
sudo apt install tightvncserver || apt install tightvncserver

mkdir -p ~/.vnc
echo '#!/bin/bash
xrdb $HOME/.Xresources
startxfce4 &' > ~/.vnc/xstartup
chmod +x ~/.vnc/xstartup

vncserver :1
